# -*- coding: utf-8 -*-
"""Laporan Harian Kedai Sou Space

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SeXO2LssPWVwx4pejDHAHXckuXbtcuqA
"""

raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

# 1. Data Splitting
# a. Memecahkan string berdasarkan titik koma (;) untuk memisahkan transaksi
transaksi = raw_log.split(';')

# b. Memecahkan tiap transaksi berdasarkan tanda pagar (#)
transaksi1_parts = transaksi[0].split('#')
transaksi2_parts = transaksi[1].split('#')

# 2. Advanced Cleaning
# a & b. Menggunakan replace() dan strip() untuk membersihkan data
transaksi1_id = transaksi1_parts[0].replace("ID:", "").strip()
transaksi1_nama = transaksi1_parts[1].replace("NAMA:", "").strip()
transaksi1_qty = transaksi1_parts[2].replace("QTY:", "").strip()
transaksi1_price = transaksi1_parts[3].replace("PRICE:", "").strip()

transaksi2_id = transaksi2_parts[0].replace("ID:", "").strip()
transaksi2_nama = transaksi2_parts[1].replace("NAMA:", "").strip()
transaksi2_qty = transaksi2_parts[2].replace("QTY:", "").strip()
transaksi2_price = transaksi2_parts[3].replace("PRICE:", "").strip()

# 3. Transformasi & Casting
# a & b. Mengubah nama menu menjadi Title Case
transaksi1_nama = transaksi1_nama.title()
transaksi2_nama = transaksi2_nama.title()

# c. Melakukan Casting menjadi Integer
transaksi1_qty = int(transaksi1_qty)
transaksi1_price = int(transaksi1_price)

transaksi2_qty = int(transaksi2_qty)
transaksi2_price = int(transaksi2_price)

# 4. Perhitungan Aritmatika
# a. Hitung subtotal untuk tiap transaksi
transaksi1_subtotal = transaksi1_qty * transaksi1_price
transaksi2_subtotal = transaksi2_qty * transaksi2_price

# b. Hitung Total Pendapatan (Subtotal 1 + Subtotal 2)
total_pendapatan = transaksi1_subtotal + transaksi2_subtotal

# 5. Output Laporan
print("============================================================")
print("               LAPORAN HARIAN KEDAI SOU SPACE               ")
print("============================================================")
print(f"{'MENU':<32}{'QTY':<8}{'HARGA':<12}{'SUBTOTAL'}")
print("------------------------------------------------------------")
print(f"{transaksi1_nama:<32}{transaksi1_qty:<8}{transaksi1_price:<12}{transaksi1_subtotal}")
print(f"{transaksi2_nama:<32}{transaksi2_qty:<8}{transaksi2_price:<12}{transaksi2_subtotal}")
print("------------------------------------------------------------")
print(f"{'TOTAL PENDAPATAN HARI INI:':<32}Rp {total_pendapatan}")
print("============================================================")