# -*- coding: utf-8 -*-
"""Tugas Kelompok 7

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17QaUBcoDZ7uwSuK7sRgmLv99SxKxbZb9
"""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "

#membersihkan spasi dan tanda pagar di 001
output = data_kotor.strip ( )
output = output.replace ("#", "")

# untuk memisahkan beberapa kata-kata yang harusnya dipisahkan tapi belum terpisah
output = output.split("-")
skill = output[3].split(",")
#menyambungkan skill dengan '&'
skill2 = " & ".join(skill)

# agar semua data bersatu
output2 = ", ".join([output[0], output[1], output[2], skill[0], skill[1], skill[2], output[4]])

# menghitung skill ada berapa skill yang ada, dan juga menghitung digit 001
output3 = (len(output[0]))
output4 = (len(skill))

# upper untuk kapital kan semua kata kata, dan title untuk kapital kan huruf pertama di setiap kata
output5 = output[2].upper()
output6 = output[1].title()
output7 = output[4].title()

# Hasilnya dari semua di atas
print("Data Mentah:", data_kotor)
print(" ")
print("========================================")
print("          HASIL VERIFIKASI DATA        ")
print("========================================")
print(f"ID Pendaftar    : {output[0]} ({output4} Digit)")
print("Nama Lengkap    :", output6,)
print("Program Studi   :", output5)
print("Skill dikuasai  :", skill2)
print("Total skill     :", output4)
print("Status Akun     :", output7)
print("========================================")