# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vy_DqrMUChfEM3kcSNKIc_2vmXP_7voi
"""

teks = 'aplikasi penulis teks modern seperti vscode / alat edit source code pakaiatom,dublime text, plus macam-macam lainnya'

print('sublime' in teks)  #output: True
print('notepad++' in teks)  #output: False

nama = 'sayu putu'

print(nama[4])   #output: i
print(nama[7])   #output: F
print(nama[1])   #output: e
print(nama[-1])  #output: i
print(nama[-3])  #output: b

judul = "Pelajaran Matematika Untuk SD"

print(judul[0:8])   #output: Pelajar
print(judul[10:15]) #output: Pelajaran
print(judul[-15:-8])#output: Matem
print(judul[-23:-15]) #output: Pelajaran Matematika Untuk
print(judul[-8:])   #output: uk SD

print(len('Indonesia'))  #output: 9
print(len('Malaysia'))   #output: 8

nomor_telepon_1 = '08712233455'
nomor_telepon_2 = '62877655300'
nomor_telepon_3 = '+6238303030'

kode_negara = '+62'

print(nomor_telepon_1.startswith(kode_negara))  # False
print(nomor_telepon_2.startswith(kode_negara))  # False
print(nomor_telepon_3.startswith(kode_negara))  # True

email1 = 'presiden@gmail.com'
email2 = 'presiden@outlook.com'

print(email1.endswith('gmail.com'))  # True
print(email2.endswith('gmail.com'))  # False