# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1plvSVCQ3X7j3LOZL9aJaJ8YALqia3QSM

*   nama: sayu putu suliastini
*   npm: 2451012030
"""

!pip install pyTelegramBotApi

import telebot
import requests

TOKEN = "8606448182:AAFTKn55jBdzxs40eSaeS6H0_OaGsdLLWac"
bot = telebot.TeleBot(TOKEN)

@bot.message_handler(commands=['start'])
def start(message):
    bot.reply_to(message, "Halo! Bot aktif.")

def get_quote():
    url = "https://quotes.liupurnomo.com/api/quotes/random"
    data = requests.get(url).json()
    return data["data"]["text"]

@bot.message_handler(commands=['quote'])
def quote(message):
    bot.reply_to(message, get_quote())

def get_jokes_bapak():
  url = "https://candaan-api.vercel.app/api/text/random"
  data = requests.get(url).json()
  return data["data"]

@bot.message_handler(commands=['jokesbapak'])
def jokesbapak(message):
    bot.reply_to(message, get_jokes_bapak())

@bot.message_handler(commands=['whoareyou'])
def jokesbapak(message):
    bot.reply_to(message, "hai, saya buatan npm: 2451012030, Nama: Sayu putu")

bot.infinity_polling()