# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JVTI5pZun6kX6Eg5ztDi-rLp3GVC9KJ
"""

nama = "sayu"
asal = "indonesia"
print(nama + asal)

print(nama)

print(nama, asal)

print("halo nama saya", nama)

print("halo nama saya", nama, "asal saya dari", asal)

data_lengkap = nama + asal
print(data_lengkap)

"""string + non string"""

asal_kota = "lampung"
kode_pos = 34152
asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota *3
print(asal_kota_x3)