# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N1qJkLod8IJbFNBmfRiKWNi0MhyOqvFa
"""

nama = 'sayu'
usia = 21
gadis = True

print(type(nama))
print(type(usia))
print(type(gadis))

usia = input('masukan usia anda')
print(type(usia))

nama= 'sayu'
tahun_lahir = 2005
print(nama + 'lahir ditahun' + str(tahun_lahir))

panjang = input('masukan panjang:')
lebar = input('masukan lebar:')

panjang =int(input('masukan panjang:'))
lebar = float(input('masukan lebar:'))
print('luas =', panjang + lebar)

masukan panjang: 10
masukanlebar: 5
luas = 50,0