# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rkgl--fDyT9w5Wj4jPoYL2Eu3s21k7jk
"""

template = 'Halo, saya %s dari %s'
print (template % ('sayu putu', 'indonesia'))

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'saya suka makan {} dan minum {}'
print(template .  format (nama='sayu putu', asal = ' indonesia'))
print(template_2 . format ('sushi' , 'matcha'))
alamat = 'Lampung, Bandar Lampung, Indonesia'
print(alamat . split())
print('halo selamat pagi!' . upper())

print('daun tidak pernah membenci angin' . title())
print('LASKAR PELANGI' . title())

print('Indonesia Adalah Negara Kepulauan'. swapcase())
print('Aku Cinta Negeriku' . swapcase())

angka = '12345'

print('Index angka 3;' , angka.find('3'))
print('Index angka 45;', angka.find ('45'))
print('Index angka 35;', angka.find ('35'))

ibu_kota = 'jakarta'
print(ibu_kota . replace('a', 'i'))
print(ibu_kota . replace('kar', 'yu'))

paragraf = 'baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf . count('di')

print(f'kata "di" muncul sebanyak {x} kali')